
branches:
 only:
  - master-with-ci

language: python

matrix:
  include:

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7.0

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6.5

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.5.5

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.4.8

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.15

cache:
  directories:
    - $HOME/.pyenv/versions/3.7.0
    - $HOME/.pyenv/versions/3.6.5
    - $HOME/.pyenv/versions/3.5.5
    - $HOME/.pyenv/versions/3.4.8
    - $HOME/.pyenv/versions/2.7.15
    - $HOME/downloads

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $HOME/bin; ln -s $(which pip2) $HOME/bin/pip; fi
  - pip install -U scikit-ci scikit-ci-addons
  - ci_addons --install ../addons

install:
  - ci install

script:
  - ci test

after_success:
  - ci after_test

deploy:
  # deploy-release
  - provider: script
    script: pwd && ls dist;echo "deploy-release" && pip install twine && twine upload --repository-url https://test.pypi.org/legacy/ dist/*
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      tags: true
  # deploy-master
  - provider: script
    script: pwd && ls dist;echo "deploy-master" && ci_addons publish_github_release ${TRAVIS_REPO_SLUG} --prerelease-sha "master-with-ci" --prerelease-packages "dist/*.whl" --re-upload
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      branch: master-with-ci

env:
  global:
    # GITHUB_TOKEN
    - secure: "YGbQpqZvUBh1zW8i876Xce6o+neH6JO4epjOCsVIa+9bWVSZD59woH/iyn6mXy9Y3fPqwuAerVjR+Ch6ETxAwZM+PBO+MY8O6JXZtvV1GpJkZOOE4SZav8C5t4MsqqsgyU4EsQSefg+R3CM2z6k8G1NrtLb6t/tLrfVLphesbXGj7AxeJz4UQfiIQa9JQBB12rYByjnOJzloVV+V3FW2VKOe6k8KUky9FRSxUKiQQQHRbunEufyucFjRtE39gbsvC47NlIZ0YfQrhQsSmcOJXUCh9dFttz6x/QTIeBvALZ4PJuz8Vu25b3azCaQVNOP46uGyjk0V5BVLaBQA7DxGMlnKXPkP+gtzTvvKN9CkmCOPg2u0A0xc2R1PVbw+mrBHX02ZtnmG9HpaanqKXzoeQwmAPLx81dehBY+dQYbWUDgCGdis7+5hzqlwM+I5XhuMFM8dfQ4fN9j9QiygJpn0cuCchf22KBosUousAQlMlzvVimIoU1FG5NQsfW/tGzBrXz2x3aQg6xgIxH0/vOd49Y3yllzoFklTE2eC9paVNsBcM9gOLpdCtO/lHJbv2EX4gQZLal/Ic+1UPwGTi3L3HkbTkK7/7TU+oFSr4qTeHteEPumnbskXo3v6qMJ6gcd3D0bmZdWzikTh4n88AcGnrqOIVozUmk7tZWgQgQdhCxY="
    # PYPI_USER
    - secure: "PB/PL0INcMiFDRRQAbmNdrNqXGSHM3fg2eeblXqlHEkk+vPO7DftXoPh7Uc+NT+pVBegq78F0wtAqLttYx0gnCVgzJeaiz7UvD+I1q4S9aUrrmgzNgbeuJOF0Yq7gWmdPWiFgSxs69zinl7klodL2hihGlsJuudRKZKivNqNUNsOO22divvlpIUafmysZgX8CkVNwYA9Rs53Udfq7giqm/4SoD/KziFM0sXz+TuzEPOSwyTG41IW15qsmOwmhdAMRai+y2uuV49iWfS75nDOgxSp6sVrUgHhNuxlVZMpCxF7Ta5knHdWvv7CpFT3yxqGhGPrw8tNAnjAoIV0W9XpeLmeotQweAPKFCq5Dlkv7DJQH0amC7q8PKgNDEyBJ6+UwuUSnr4p2yvUdb6zJxiC6tsAxAkx6dcKcRrvqyYIFkyFD4OHKOLx+6XHw5e043hHhIz6K8XcWxj1wC0fTkiMhyaiUqiw5YImZRRQasVzF8uN6aySv2diMD0I9rvJWJoIy+pIIP5gWwFqiF/90OBBoONFmGMNtcTmgLGu2tZU0oHAWH/NoIhUztf25RRgR6FePisSVoPFk3PPmDUvGAtsSGoUcbLU2xxFY9e5aDavYUSsU43OI506PXnnXlTq9Deh6GUNf+IpVMdoGmusBb07S9BhbV9aEDOvRvXcrPIlXpw="
    # PYPI_PASSWORD
    - secure: "EJZF4WXZhbKFVytkjEnv9gqHMCr9ldDox9v+lOIMkb8pprDEbRFuyi9xEQtJCvnRs2FMoonvX0j4hwd646wwQEfKvIQvVUXTAoikLWnQac+qbR/eMeuBAjrszQ6TvwxNM0aLP6Xkn8hwq8kkiA75Rh8Hnom3zKZWbU2p3jqbUV7ep/nP4ncpDxdmYPn/bv82ZYyHVCqJ9Nz5ni30lUxcNCab8zvwQSM7ZrpJCsjM8+hnRtidWLMyykGWJ8Ga1XX6G37VNWEUR5828Hn0Ky77vFrMkITOWqpM4TvtJseAmPpWRlT+pWvXzhLRmRYfmBcW8twqocMFvX8Ryu6NMxgdUq2sy7vJJYjuxBYZWM+N457706p8IE/GT2Ev2bCwjHFmXB1vYzFV93fMo+WzzcGlUSC6Zh33QN8UWVobEtA5YVxrwY0JsTz0h4zegsS7XHbmuntS9U0gpY11Z0YWNL7CFVi74pz62QgPWChrZjkK9iriFfuAsxauHFB5DH9WRntQGepJZWCokr+qbvIokEGZqZwJKVf9h3b3xucJG/gsLkaKXw/8lbcQiw0fXm3sGI3/V1HMmZ64e1vMj7R9IsXOee+fdLKO8iXGPZXtTs4SAeUgIwEmqB1DwXV1Yo9dsa7PCREt8YFV4schRzmdyup+sAX8FXDcPOUcFv84AvASgck="
