
branches:
 only:
  - master-with-ci

version: "0.0.1.{build}"

environment:
  matrix:

    # Visual Studio (Python 2 & 3, 32 & 64 bit)
    - PYTHON_DIR: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"

    - PYTHON_DIR: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"

    - PYTHON_DIR: "C:\\Python34"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"

    - PYTHON_DIR: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"

    - PYTHON_DIR: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"

    - PYTHON_DIR: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"

    - PYTHON_DIR: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"

    - PYTHON_DIR: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"

#    - PYTHON_DIR: "C:\\Python37"
#      PYTHON_VERSION: "3.7.x"
#      PYTHON_ARCH: "32"
#      BLOCK: "0"
#
#    - PYTHON_DIR: "C:\\Python37-x64"
#      PYTHON_VERSION: "3.7.x"
#      PYTHON_ARCH: "64"
#      BLOCK: "0"

  GITHUB_TOKEN:
    secure: 0AQn9ahwWioFTIZE5Ft+6OnGuj6kgCdLtzdyiDCOrmAHxGh/Hl5erpU6dPF4YyQz
  PYPI_USER:
    secure: FSD2hc+aSqlOLncSKl12Dw==
  PYPI_PASSWORD:
    secure: Njw5/Y55cp561BNOqvff/amo5ZeHTMggWoSaVpvE51c=

  # Needed by "publish_github_release" add-on to workaround issue appveyor/ci#1493
  APPVEYOR_API_TOKEN:
    secure: hrNo4O4PKuIZ5I4ESgDrDxdJcIDMpN+kB0J6PHQKOgY=

init:
  - python -m pip install -U scikit-ci scikit-ci-addons
  - python -m ci_addons --install ../addons

  - ps: ../addons/appveyor/rolling-build.ps1

install:
  - python -m ci install

build_script:
  - python -m ci build

test_script:
  - python -m ci test

after_test:
  - python -m ci after_test

on_finish:
  - ps: ../addons/appveyor/enable-worker-remote-access.ps1 -check_for_block

deploy_script:
  - ps: |
      if ($env:appveyor_repo_tag -eq $true -and $env:appveyor_repo_tag_name –match "^v[0-9]+(\.[0-9]+)*") {
        Write-Host "deploy release"
        pip install twine
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*
      } elseif ($env:appveyor_repo_branch -eq "master-with-ci") {
         Write-Host "deploy master"
         ci_addons publish_github_release $env:appveyor_repo_name `
              --prerelease-sha "master-with-ci" `
              --prerelease-packages "dist/*.whl" --re-upload
      } else {
        Write-Host "nothing to deploy"
      }

matrix:
  fast_finish: false

